// Code generated by 'yaegi extract github.com/elgopher/pi/image'. DO NOT EDIT.

package lib

import (
	"reflect"

	"github.com/elgopher/pi/image"
)

func init() {
	Symbols["github.com/elgopher/pi/image/image"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DecodePNG": reflect.ValueOf(image.DecodePNG),

		// type definitions
		"Image": reflect.ValueOf((*image.Image)(nil)),
		"RGB":   reflect.ValueOf((*image.RGB)(nil)),
	}
}
