// Code generated by 'yaegi extract github.com/elgopher/pi/font'. DO NOT EDIT.

package lib

import (
	"reflect"

	"github.com/elgopher/pi/font"
)

func init() {
	Symbols["github.com/elgopher/pi/font/font"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Load": reflect.ValueOf(font.Load),
	}
}
