// Code generated by 'yaegi extract github.com/elgopher/pi/snap'. DO NOT EDIT.

package lib

import (
	"reflect"

	"github.com/elgopher/pi/snap"
)

func init() {
	Symbols["github.com/elgopher/pi/snap/snap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Take": reflect.ValueOf(snap.Take),
	}
}
