name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  all:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ 1.18 ]
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Install chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install wasmbrowsertest
        run: go install github.com/agnivade/wasmbrowsertest@latest

      - name: Setup wasmexec
        run: mv $(go env GOPATH)/bin/wasmbrowsertest $(go env GOPATH)/bin/go_js_wasm_exec

      - name: Test in the browser
        run: GOOS=js GOARCH=wasm go test -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3.3.0
        with:
          args: "-v"
          version: v1.50.1

      - name: Generate coverage report
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
