name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  all:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ 1.18 ]
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: "-v"
          version: v1.47.1

      - name: Generate coverage report
        run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
